doc: platform: cznic: turris-omnia-mcu: Fix sphinx-build warning
Fix sphinx-build warnings
  ERROR: Unexpected indentation.
  WARNING: Block quote ends without a blank line; unexpected unindent
in Documentation/ABI/testing/sysfs-bus-i2c-devices-turris-omnia-mcu.

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Link: https://lore.kernel.org/all/20240702174938.04c12aab@canb.auug.org.au/
Fixes: 20d35a68b2d2 ("platform: cznic: turris-omnia-mcu: Add support for MCU connected GPIOs")
Tested-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Marek Behún <kabel@kernel.org>
Link: https://lore.kernel.org/r/20240730144924.25552-2-kabel@kernel.org
Signed-off-by: Arnd Bergmann <arnd@arndb.de>