scsi: aic7xxx: Fix firmware build fatal error
When building with CONFIG_AIC7XXX_BUILD_FIRMWARE=y, two fatal errors
are reported as shown below:

  aicasm_gram.tab.c:203:10: fatal error: aicasm_gram.tab.h:
  No such file or directory

  aicasm_macro_gram.tab.c:167:10: fatal error: aicasm_macro_gram.tab.h:
  No such file or directory

Fix these issues to make randconfig builds more reliable.

[mkp: add missing include]

Signed-off-by: Wang Jinchao <wangjinchao@xfusion.com>
Link: https://lore.kernel.org/r/ZK0XIj6XzY5MCvtd@fedora
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>