dt-bindings: fix compilation error of the example in marvell,mmp3-hsic-phy.yaml
Running `make dt_binging_check`, gives the error:

DTC     Documentation/devicetree/bindings/phy/marvell,mmp3-hsic-phy.example.dt.yaml
Error: Documentation/devicetree/bindings/phy/marvell,mmp3-hsic-phy.example.dts:20.41-42 syntax error
FATAL ERROR: Unable to parse input tree

This is because the example uses the macro GPIO_ACTIVE_HIGH which
is defined in gpio.h but the include of this header is missing.
Add the include to fix the error.

Fixes: 85027f5ff2ba ("dt-bindings: phy: Add binding for marvell,mmp3-hsic-phy")
Link: https://lore.kernel.org/r/20200124105753.15976-1-dafna.hirschfeld@collabora.com
Signed-off-by: Dafna Hirschfeld <dafna.hirschfeld@collabora.com>
Acked-by: Rob Herring <robh@kernel.org>
Signed-off-by: Olof Johansson <olof@lixom.net>