usb: typec: mux: fix static inline syntax error
Fix build error when USB_SUPPORT is not set or TYPEC is not set
by dropping an extraneous semi-colon:

In file included from ../drivers/phy/qualcomm/phy-qcom-qmp-combo.c:23:
../include/linux/usb/typec_mux.h:77:1: error: expected identifier or '(' before '{' token
   77 | {
      | ^
../include/linux/usb/typec_mux.h:76:33: warning: 'fwnode_typec_mux_get' used but never defined
   76 | static inline struct typec_mux *fwnode_typec_mux_get(struct fwnode_handle *fwnode);
      |                                 ^~~~~~~~~~~~~~~~~~~~

Fixes: 9ec61dead67a ("usb: typec: mux: Remove alt mode parameters from the API")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Cc: linux-usb@vger.kernel.org
Link: https://lore.kernel.org/r/20230601050325.26883-1-rdunlap@infradead.org
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>