Revert part of d2ca0f6b857d ("ARM: 9304/1: add prototype for function called only from asm")
The build bot reports:

>> arch/arm/vfp/vfpmodule.c:324:13: error: static declaration of 'VFP_bounce' follows non-static declaration
   static void VFP_bounce(u32 trigger, u32 fpexc, struct pt_regs *regs)
               ^
   arch/arm/include/asm/vfp.h:105:6: note: previous declaration is here
   void VFP_bounce(u32 trigger, u32 fpexc, struct pt_regs *regs);
        ^
   1 error generated.

This is due to a merge conflict between commit d2ca0f6b857d ("ARM:
9304/1: add prototype for function called only from asm") and Ard's
commit 348e3ee05cae ("ARM: vfp: Reimplement VFP exception entry in C
code").

Fix this by removing Arnd's change. No need to backport.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202308150547.m54XHV12-lkp@intel.com/
Signed-off-by: Russell King (Oracle) <rmk+kernel@armlinux.org.uk>