mfd: sl28cpld: Depend on I2C
Fixes the following randconfig build error:

 ld: drivers/mfd/simple-mfd-i2c.o: in function `simple_mfd_i2c_probe':
 simple-mfd-i2c.c:(.text+0x48): undefined reference to `__devm_regmap_init_i2c'
 ld: drivers/mfd/simple-mfd-i2c.o: in function `simple_mfd_i2c_driver_init':
 simple-mfd-i2c.c:(.init.text+0x14): undefined reference to `i2c_register_driver'
 ld: drivers/mfd/simple-mfd-i2c.o: in function `simple_mfd_i2c_driver_exit':
 simple-mfd-i2c.c:(.exit.text+0xd): undefined reference to `i2c_del_driver'

Reported-by: Randy Dunlap <rdunlap@infradead.org>
Tested-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
Acked-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Lee Jones <lee.jones@linaro.org>