s390/3270: make raw3270_state_final() depend on CONFIG_TN3270_CONSOLE
If CONFIG_TN3270_CONSOLE is not enabled clang emits the following warning:

drivers/s390/char/raw3270.c:114:19:
  error: unused function 'raw3270_state_final' [-Werror,-Wunused-function]
static inline int raw3270_state_final(struct raw3270 *rp)

Get rid of this warning by making raw3270_state_final() only
available if CONFIG_TN3270_CONSOLE is enabled.

Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
Signed-off-by: Alexander Gordeev <agordeev@linux.ibm.com>