ARM: disallow PCI with MMU=n again
My cleanup patch allowed enabling PCI on MMU-less builds,
which breaks for at least one driver and is never required:

   In file included from include/linux/irqchip/arm-gic-v3.h:604,
                    from drivers/pci/controller/pcie-iproc.c:17:
   arch/arm/include/asm/arch_gicv3.h: In function 'write_ICC_EOIR1_EL1':
arch/arm/include/asm/arch_gicv3.h:44:9: error: implicit declaration of function 'write_sysreg' [-Werror=implicit-function-declaration]

Fixes: cce2dd28dd21 ("ARM: Kconfig: clean up platform selection")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>