Revert "drm/msm/mdp5: provide dynamic bandwidth management"
This reverts commit 239dc552fcaca537ffc647f38423c227ddc6aeda.

Breaks armv7 build

  ERROR: modpost: "__aeabi_ldivmod" [drivers/gpu/drm/msm/msm.ko] undefined!

Signed-off-by: Rob Clark <robdclark@chromium.org>